In [5]:
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
import numpy as np

img = mpimg.imread('/content/dog.jpeg')


Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 44.0MB/s]


In [7]:
# (Max(RGB) + Min(RGB)) / 2
def color2grayscale_lightness(vector):
  max = np.max(vector)
  min = np.min(vector)
  return (max + min) / 2

gray_img_01 = np.apply_along_axis(color2grayscale_lightness, 2, img)
gray_img_01[0,0]

<ipython-input-7-976ff7f9bde4>:5: RuntimeWarning: overflow encountered in scalar add
  return (max + min) / 2


102.5

In [4]:
def color2grayscale_average(vector):
  return np.average(vector)

gray_img_02 = np.apply_along_axis(color2grayscale_average, 2, img)
gray_img_02[0,0]

107.66666666666667

In [8]:
def color2grayscale_luminosity(vector):
  return 0.21 * vector[0] + 0.72 * vector[1] + 0.07 * vector[2]

gray_img_03 = np.apply_along_axis(color2grayscale_luminosity, 2, img)
gray_img_03[0,0]

126.22999999999999

In [10]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
data

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 12.5MB/s]


array([[230.1,  37.8,  69.2,  22.1],
       [ 44.5,  39.3,  45.1,  10.4],
       [ 17.2,  45.9,  69.3,  12. ],
       [151.5,  41.3,  58.5,  16.5],
       [180.8,  10.8,  58.4,  17.9],
       [  8.7,  48.9,  75. ,   7.2],
       [ 57.5,  32.8,  23.5,  11.8],
       [120.2,  19.6,  11.6,  13.2],
       [  8.6,   2.1,   1. ,   4.8],
       [199.8,   2.6,  21.2,  15.6],
       [ 66.1,   5.8,  24.2,  12.6],
       [214.7,  24. ,   4. ,  17.4],
       [ 23.8,  35.1,  65.9,   9.2],
       [ 97.5,   7.6,   7.2,  13.7],
       [204.1,  32.9,  46. ,  19. ],
       [195.4,  47.7,  52.9,  22.4],
       [ 67.8,  36.6, 114. ,  12.5],
       [281.4,  39.6,  55.8,  24.4],
       [ 69.2,  20.5,  18.3,  11.3],
       [147.3,  23.9,  19.1,  14.6],
       [218.4,  27.7,  53.4,  18. ],
       [237.4,   5.1,  23.5,  17.5],
       [ 13.2,  15.9,  49.6,   5.6],
       [228.3,  16.9,  26.2,  20.5],
       [ 62.3,  12.6,  18.3,   9.7],
       [262.9,   3.5,  19.5,  17. ],
       [142.9,  29.3,  12.6,  15. ],
 

In [11]:
sales_data = data[:,3]
sales_data

array([22.1, 10.4, 12. , 16.5, 17.9,  7.2, 11.8, 13.2,  4.8, 15.6, 12.6,
       17.4,  9.2, 13.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 17.5,
        5.6, 20.5,  9.7, 17. , 15. , 20.9, 18.9, 10.5, 21.4, 11.9, 13.2,
       17.4, 11.9, 17.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 17.9,
        8.5, 16.1, 10.6, 23.2, 19.8,  9.7, 16.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 20.7, 14. , 16. , 11.3,
       11. , 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 17.3, 11.3, 13.6, 21.7, 20.2, 12. , 16. ,
       12.9, 16.7, 14. ,  7.3, 19.4, 22.2, 11.5, 16.9, 16.7, 20.5, 25.4,
       17.2, 16.7, 23.8, 19.8, 19.7, 20.7, 15. ,  7.2, 12. ,  5.3, 19.8,
       18.4, 21.8, 17.1, 20.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 16.6, 15.2, 19.7, 10.6,  6.6, 11.9, 24.7,  9.7,  1.6, 17.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 12.3, 10.3, 18.2, 25.4, 10.9, 10.1, 16

In [12]:
sales_max = np.max(sales_data)
sales_index = np.argmax(sales_data)
sales_max, sales_index

(27.0, 175)

In [13]:
tv_data = data[:,0]
tv_data

array([230.1,  44.5,  17.2, 151.5, 180.8,   8.7,  57.5, 120.2,   8.6,
       199.8,  66.1, 214.7,  23.8,  97.5, 204.1, 195.4,  67.8, 281.4,
        69.2, 147.3, 218.4, 237.4,  13.2, 228.3,  62.3, 262.9, 142.9,
       240.1, 248.8,  70.6, 292.9, 112.9,  97.2, 265.6,  95.7, 290.7,
       266.9,  74.7,  43.1, 228. , 202.5, 177. , 293.6, 206.9,  25.1,
       175.1,  89.7, 239.9, 227.2,  66.9, 199.8, 100.4, 216.4, 182.6,
       262.7, 198.9,   7.3, 136.2, 210.8, 210.7,  53.5, 261.3, 239.3,
       102.7, 131.1,  69. ,  31.5, 139.3, 237.4, 216.8, 199.1, 109.8,
        26.8, 129.4, 213.4,  16.9,  27.5, 120.5,   5.4, 116. ,  76.4,
       239.8,  75.3,  68.4, 213.5, 193.2,  76.3, 110.7,  88.3, 109.8,
       134.3,  28.6, 217.7, 250.9, 107.4, 163.3, 197.6, 184.9, 289.7,
       135.2, 222.4, 296.4, 280.2, 187.9, 238.2, 137.9,  25. ,  90.4,
        13.1, 255.4, 225.8, 241.7, 175.7, 209.6,  78.2,  75.1, 139.2,
        76.4, 125.7,  19.4, 141.3,  18.8, 224. , 123.1, 229.5,  87.2,
         7.8,  80.2,

In [14]:
tv_average = np.average(tv_data)
tv_average

147.0425

In [15]:
sales_counter = np.sum(sales_data >= 20)
sales_counter

40

In [16]:
sales_cond = sales_data >= 15
radio_data = data[:,1]
radio_cond = radio_data * sales_cond
radio_mean = np.sum(radio_cond)/np.sum(sales_cond)
radio_mean

26.222935779816517

In [17]:
newspaper_data = data[:,2]
newspaper_mean = newspaper_data.mean()
newspaper_cond = newspaper_data > newspaper_mean

sales_cond = sales_data * newspaper_cond
sales_sum = np.sum(sales_cond)
sales_sum

1405.1

In [22]:
sales_mean = sales_data.mean()
score_sales = np.where(sales_data > sales_mean, 'Good', np.where(sales_data < sales_mean, 'Bad','Average'))
score_sales[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')

In [20]:
average_index = np.argmin(abs(sales_data - sales_mean))
average_index

123

In [24]:
sales_closet = sales_data[average_index]
sales_closet

15.2

In [25]:
score_sales = np.where(sales_data > sales_closet, 'Good', np.where(sales_data < sales_closet, 'Bad','Average'))
score_sales[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')